# Generated by Django 5.2.1 on 2025-06-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_student_phone_number_alter_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
