# Generated by Django 5.2.1 on 2025-06-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('period_number', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('classroom', models.CharField(blank=True, max_length=100)),
                ('course', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('section', models.CharField(max_length=10)),
            ],
        ),
    ]
