# Generated by Django 5.2.1 on 2025-06-11 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_attendance_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='course',
        ),
    ]
