# Generated by Django 5.2.1 on 2025-06-12 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_faceembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceembedding',
            name='image_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='home.student'),
        ),
    ]
