# Generated by Django 5.2.1 on 2025-06-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_teachersubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='eid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TeacherSubject',
        ),
    ]
