# Generated by Django 5.2.1 on 2025-06-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_timetableentry_eid_delete_teachersubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
